general {
    lock_cmd = pidof hyprlock || hyprlock       # Bloquea con hyprlock
    before_sleep_cmd = loginctl lock-session    # Asegura bloqueo antes de suspender/hibernar
    after_sleep_cmd = hyprctl dispatch dpms on  # Fuerza encendido de pantalla al despertar
}

# 5 Minutos (300s): Bloquear la sesión
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 5.5 Minutos (330s): Apagar el monitor (Ahorro de energía)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 15 Minutos (900s): Hibernación completa del sistema
listener {
    timeout = 900
    on-timeout = systemctl hibernate
}