general {
    lock_cmd = pidof hyprlock || hyprlock       # Bloquea con hyprlock
    before_sleep_cmd = loginctl lock-session    # Asegura bloqueo antes de suspender/hibernar
    after_sleep_cmd = hyprctl dispatch dpms on  # Fuerza encendido de pantalla al despertar
}

# 10 Minutos (600s): Bloquear la sesión
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 15 Minutos (900s): Apagar el monitor (Ahorro de energía)
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 20 Minutos (1200s): Hibernación completa del sistema
listener {
    timeout = 1200
    on-timeout = systemctl hibernate
}